### ISSUE TITLE
close event

### ISSUE THREAD

**Issue by mitselek** [mishk0/slack-bot-api#18]
What are my options if socket is closed for some reason? I have to have an option to reconnect somehow.

**Comment by Starfox64** [comment]
You could call the [**login()**](https://github.com/mishk0/slack-bot-api/blob/master/index.js#L28) method, it should restart an RTM session.

**Comment by mitselek** [comment]
It usually closes the connection immediately after login. Might there be some limit on number of simultaneous sockets per one user? I do have around 20 bot instances deployed using same credentials.

**Comment by Starfox64** [comment]
If you suspect that sockets are being closed because of how many instances are running, I would suggest to listen for error events on the socket and look if your sockets are being rate limited. According to the [API documentation](https://api.slack.com/docs/rate-limits) continuing to send request after being rate limited will get your application disconnected.

**Comment by mitselek** [comment]
They get disconnected even when not rate limited. They really don't talk much - 2-3 messages per hour per instance so total messages are around 40 messages/hour

**Comment by mishk0** [comment]
Your question is how to reconnect or why connection sometimes closes immediately?

For reconnection you can simply invoke `login` method.
Is second problem connected with this issue https://github.com/mishk0/slack-bot-api/issues/20?

**Comment by mitselek** [comment]
My question as of today is, if anyone knows why sockets get closed, if there are more than 17 instances of same bot user. I think this should be asked from slack team instead :)
Otherwise login method works as expected and thank You both for this.
